keel:
  image:
    repository: harbor.zulong.com/keel-images
    pullSecrets:
      - name: "zulong-key"
  ingress:
    name: nginx
  apps:
  - name: sdkserver
    version: v5297.1
    tag: v5297
    replicas: 2
    resources:
      memory: 6G
    nodeAffinity:
      key: keel/node
      value: sdkserver
    javaOpts: ""
    service:
      ports:
      - port: 8080
      - port: 8009
    ingress:
      host: sdkserver.zulong.com
      secret: keel-secret
      port: 8080
      rules:
        - path:
           - "/"
          allow:
            - 10.236.254.0/24
          deny: []
        - path: ["/images/", "/js/", "/css/"]
          disableAccessLog: true
          snippet: |
            proxy_set_header X-Forwarded-For $remote_addr;
            proxy_redirect http:// https://;
        - path: ["/api/validate"]
          exactMatch: true
          disableAccessLog: true
    log:
      hostPath: /data/keel/sdkserver
      path: /export/logs/
    configPath: /etc/sdkserver_config
    crontabPath: /crontab
    update:
      wait: ""
      http:
        path: "/api/validate?appid=iprojectios&username=10542&token=2nGbR9ui1fD3v3uzKhMaQMTNYkoXhWTAXqYU6FNrupksSU45ZL1EQriizhzuMRXkwi6VWR6VmfFnyhzGh41j9woR&loginip=1984621578&version=1.0&device_uuid=5688225dc53eb695df7eac4c400505a8e560d45e"
        port: 8080
      script: ""
  - name: gmsp
    replicas: 1
    tag: v5316
    resources:
      memory: 1024M
    javaOpts: "-Xmx1024m -Xms1024m"
    service:
      type: NodePort
      ports:
        - port: 8080
          nodePort: 31011
    log:
      hostPath: /data/keel/gmsp
      path: /export/logs/
    configPath: /usr/local/tomcat/gmsp_config
    update: {}