keel:
  image:
    repository: harbor.zulong.com/keel-images
    pullSecrets:
      - name: "zulong-key"
  storage:
    local: true
    className: ""
  ingress:
    name: nginx
  rabbitmq:
    cluster:
      enabled:
      name: keel-rabbitmq
      image: harbor.zulong.com/common-images/rabbitmq:3.11
      serviceType: NodePort
      replicas: 1
      storage: 10Gi
      resources:
        cpu: 1000m
        memory: 2Gi
      additionalConfig: |
        total_memory_available_override_value = 1600Mi
      username: zulongrc
      password: Zulong@123.com
    exchange:
      - name: direct_SDK
        type: direct
        binding:
          - queue: charge_SDK
            key: charge_SDK
          - queue: charge_SDK
            key: login_SDK
          - queue: checkreceipt_SDK
            key: checkreceipt_SDK
          - queue: login_SDK
            key:
          - queue: login_SDK
            key: login
          - queue: login_SDK
            key: login_SDK
          - queue: login_sdk_to_rc
            key: login
          - queue: register_SDK
            key: register_SDK
          - queue: sendalertinfo_SDK
            key: sendalertinfo_SDK
          - queue: test_queue
            key: test
          - queue: voided_slave
            key: voided_slave
      - name: qrcode_login_fanout_SDK
        type: fanout
      - name: qrcode_pay_fanout_SDK
        type: fanout
        binding:
          - queue: qrcode_pay_SDK1
          - queue: qrcode_pay_SDK2
    queue:
      - name: login_SDK
      - name: login_sdk_to_rc
      - name: charge_SDK
      - name: checkreceipt_SDK
      - name: sendalertinfo_SDK
      - name: register_SDK
      - name: qrcode_login_SDK
      - name: qrcode_pay_SDK
      - name: qrcode_pay_SDK1
      - name: qrcode_pay_SDK2
      - name: test_queue
      - name: voided_slave
  apps:
  - name: sdkserver
    tag: 5332
    replicas: 2
    resources:
      memory: 6G
    nodeAffinity:
      key: keel/node
      value: sdkserver
    javaOpts: ""
    service:
      ports:
      - port: 8080
      - port: 8009
    ingress:
      host: sdkserver.zulong.com
      secret: keel-secret
      port: 8080
      rules:
        - path:
           - "/"
          allow:
            - 10.236.254.0/24
          deny: []
        - path: ["/images/", "/js/", "/css/"]
          disableAccessLog: true
          snippet: |
            proxy_set_header X-Forwarded-For $remote_addr;
            proxy_redirect http:// https://;
        - path: ["/api/validate"]
          exactMatch: true
          disableAccessLog: true
    log:
      hostPath: /data/keel/sdkserver
      path: /export/logs/
    configPath: /etc/sdkserver_config
    crontabPath: /crontab
    update:
      wait: ""
      http:
        path: "/api/validate?appid=iprojectios&username=10542&token=2nGbR9ui1fD3v3uzKhMaQMTNYkoXhWTAXqYU6FNrupksSU45ZL1EQriizhzuMRXkwi6VWR6VmfFnyhzGh41j9woR&loginip=1984621578&version=1.0&device_uuid=5688225dc53eb695df7eac4c400505a8e560d45e"
        port: 8080
      script: ""
  - name: riskcontrol
    tag: 5172
    replicas: 1
    resources:
      memory: 4G
    log:
      hostPath: /data/keel/riskcontrol
      path: /export/logs/RiskControl
    configPath: /etc/rcserver_config
  - name: gmsp
    replicas: 1
    tag: v5316
    resources:
      memory: 1024M
    javaOpts: "-Xmx1024m -Xms1024m"
    service:
      type: NodePort
      ports:
        - port: 8080
          nodePort: 31011
    log:
      hostPath: /data/keel/gmsp
      path: /export/logs/
    configPath: /usr/local/tomcat/gmsp_config
    update: {}