{{- if eq .Values.keel.step 0 }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: helm-hook-wait
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install, post-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation, hook-succeeded
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: helm-hook-wait
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install, post-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation, hook-succeeded
rules:
  - apiGroups: ["rabbitmq.com"]
    resources: ["rabbitmqclusters"]
    verbs: ["list", "get" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: helm-hook-wait-access
  annotations:
    "helm.sh/hook": post-install, post-upgrade
    "helm.sh/hook-weight": "-4"
    "helm.sh/hook-delete-policy": before-hook-creation, hook-succeeded
subjects:
  - kind: User
    name: system:serviceaccount:{{ .Release.Namespace }}:helm-hook-wait
    apiGroup: rbac.authorization.k8s.io
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: helm-hook-wait
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: post-install-0
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install, post-upgrade
    "helm.sh/hook-weight": "-3"
    "helm.sh/hook-delete-policy": before-hook-creation, hook-succeeded
data:
  post-install-0.sh: |
{{ .Files.Get "resources/hook/post-install-0.sh" | indent 4 }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: post-install-0
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install, post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation, hook-succeeded
spec:
  template:
    metadata:
      name: post-install-0
      labels:
        app.kubernetes.io/managed-by: {{.Release.Service | quote }}
        app.kubernetes.io/instance: {{.Release.Name | quote }}
        helm.sh/chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    spec:
      serviceAccountName: helm-hook-wait
      restartPolicy: Never
      containers:
        - name: wait-ready
          image: "harbor.zulong.com/common-images/k8s-kubectl:v1.25.4"
          command:
            - "/bin/sh"
            - "/scripts/post-install-0.sh"
            - "{{ .Release.Namespace }}"
          env:
            - name: RMQ_U
              value: {{ .Values.keel.rabbitmq.cluster.username }}
            - name: RMQ_P
              value: {{ .Values.keel.rabbitmq.cluster.password}}
          volumeMounts:
            - name: script
              mountPath: /scripts/
      volumes:
        - name: script
          configMap:
            name: post-install-0
{{- end }}
